apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    matchLabels:
      app: eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - name: eureka-service
        image: martinex453/eureka:latest
        ports:
        - containerPort: 8761
        env:
        - name: CF_HOST
          value: "config-server"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - nodePort: 30401
      protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort
