apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulate-backend
  labels:
    app: simulate-backend
spec:
  selector:
    matchLabels:
      app: simulate-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: simulate-backend
    spec:
      containers:
      - name: backend
        image: martinex453/simulateloan:latest
        ports:
        - containerPort: 8002
        env:
        - name: CF_HOST
          value: "config-server"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-simulatedb
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-user-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: simulate-backend
  labels:
    app: simulate-backend
spec:
  selector:
    app: simulate-backend
  ports:
    - nodePort: 0
      protocol: TCP
      port: 8091
      targetPort: 8002
  type: NodePort